version: "3.9"
services:
  db:
    image: library/postgres:13-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - data:/var/lib/postgresql/data
    expose: 
      - 5432
    networks:
      - telegram-bot
  web:
    image: telegram-bot:latest
    env_file:
      - .env
    ports: 
      - 3000:3000
    networks:
      - telegram-bot
volumes:
  data: {}
networks: 
  telegram-bot:
